# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2023 Ledger SAS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

option('svd', type: 'string', description: 'svd filename to use (without .svd extension',
 deprecated: 'target')

option('with-tests-only', type: 'boolean', value: false, description:
'with unittests, this disables the regular targets,' +
'use for test purpose only',
deprecated: 'with-test')

option('target', type: 'array', value: [], description: 'list of target svd files to process, empty list means all')
option('with-test', type: 'boolean', value: false, description: 'Execute auto generated test for given targets')
option('schema-validation', type: 'feature', value: 'auto', description: 'validate svd against XML schema')
