# SPDX-FileCopyrightText: 2026 H2Lab Development Team
# SPDX-License-Identifier: Apache-2.0

version = 1
# quilt patch series
[[annotations]]
path = "patches/**"
SPDX-FileCopyrightText = "2026 H2Lab Development Team"
SPDX-License-Identifier = "Apache-2.0"
