# SPDX-FileCopyrightText: 2024 Ledger SAS
#
# SPDX-License-Identifier: Apache-2.0

name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
    - name: install python requirements
      run: pip3 install -r requirements.txt
    - name: Meson Setup
      run: |
        meson setup -Dwith-test=true builddir
    - name: Patch SVDs
      run: |
        ninja -C builddir patch
    - name: Validate SVDs
      run: |
        ninja -C builddir validate
    - name: Generate Jsons
      run: |
        ninja -C builddir json
    - name: Build tests
      run: |
        ninja -C builddir
    - name: Run tests
      run: |
        ninja -C builddir test
    - name: Meson postcheck
      if: failure()
      run: |
        cat builddir/meson-logs/meson-log.txt
        cat builddir/meson-logs/testlog.txt
